# Generated by Django 4.1.1 on 2022-10-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, verbose_name='년도')),
                ('semester', models.CharField(max_length=255, verbose_name='학기')),
                ('classify', models.CharField(max_length=255, verbose_name='이수구분')),
                ('codenum', models.CharField(max_length=255, verbose_name='학수번호')),
                ('namee', models.CharField(max_length=255, verbose_name='과목명')),
                ('credit', models.CharField(max_length=255, verbose_name='학점')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
